// <auto-generated />
using System;
using FamilyPlanner.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyPlanner.Api.Migrations
{
    [DbContext(typeof(FamilyPlannerDbContext))]
    [Migration("20260518094318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FamilyPlanner.Api.Entities.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.GroceryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyAdded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantity")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceMealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceMealId");

                    b.HasIndex("WeekPlanId");

                    b.ToTable("GroceryItems");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeInstructions")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.MealIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantity")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("MealIngredients");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.PlannedDinner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomDinnerName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("WeekPlanId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("PlannedDinners");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.WeekPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeekStartDate")
                        .IsUnique();

                    b.ToTable("WeekPlans");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.GroceryItem", b =>
                {
                    b.HasOne("FamilyPlanner.Api.Entities.Meal", "SourceMeal")
                        .WithMany()
                        .HasForeignKey("SourceMealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyPlanner.Api.Entities.WeekPlan", "WeekPlan")
                        .WithMany("GroceryItems")
                        .HasForeignKey("WeekPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMeal");

                    b.Navigation("WeekPlan");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.MealIngredient", b =>
                {
                    b.HasOne("FamilyPlanner.Api.Entities.Meal", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.PlannedDinner", b =>
                {
                    b.HasOne("FamilyPlanner.Api.Entities.Meal", "Meal")
                        .WithMany("PlannedDinners")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyPlanner.Api.Entities.WeekPlan", "WeekPlan")
                        .WithMany("PlannedDinners")
                        .HasForeignKey("WeekPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("WeekPlan");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.Meal", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("PlannedDinners");
                });

            modelBuilder.Entity("FamilyPlanner.Api.Entities.WeekPlan", b =>
                {
                    b.Navigation("GroceryItems");

                    b.Navigation("PlannedDinners");
                });
#pragma warning restore 612, 618
        }
    }
}
